modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "nocheats"
version = "${version}"
displayName = "NoCheats"
description = "禁用创造模式和give指令，允许旁观模式。仅局域网主机有效。"
authors = "YourName"

[[dependencies.nocheats]]
modId = "neoforge"
mandatory = true
versionRange = "[21.11,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.nocheats]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.11]"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "nocheats.mixins.json"
