plugins {
    id 'fabric-loom' version '1.7-SNAPSHOT'
    id 'maven-publish'
    id 'java'
}

group = 'com.example'
version = '1.0.0'

base {
    archivesName = 'nocheats'
}

repositories {
    mavenLocal()
    mavenCentral()
    maven { url = "https://bmclapi2.bangbang93.com/maven" }
    maven { url = "https://mirrors.cloud.tencent.com/nexus/repository/maven-public/" }
    maven { url = "https://maven.fabricmc.net/" }
    maven { url = "https://libraries.minecraft.net/" }
}

dependencies {
    minecraft "com.mojang:minecraft:1.21.11"
    mappings "net.fabricmc:yarn:1.21.11+build.1:v2"
    modImplementation "net.fabricmc:fabric-loader:0.16.10"

    // Fabric API
    modImplementation "net.fabricmc.fabric-api:fabric-api:0.119.5+1.21.11"

    // Mixin
    include "org.spongepowered:mixin:0.8.7"
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    options.release = 21
    options.encoding = 'UTF-8'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
    withSourcesJar()
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.archivesName}"}
    }
}
