plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '1.0.23'
}

group = 'com.example'
version = '1.0.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenLocal()
    mavenCentral()
    maven { url = "https://bmclapi2.bangbang93.com/maven" }
    maven { url = "https://mirrors.cloud.tencent.com/nexus/repository/maven-public/" }
    maven { url = "https://maven.neoforged.net/releases" }
}

dependencies {
    implementation "net.neoforged:neoforge:21.11.42"
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

neoForge {
    version = "21.11.42"
    
    runs {
        client { client() }
        server { server() }
    }
    
    mods {
        nocheats {
            sourceSet(sourceSets.main)
        }
    }
}

processResources {
    def replaceProperties = [version: version]
    inputs.properties replaceProperties
    filesMatching("META-INF/neoforge.mods.toml") {
        expand replaceProperties
    }
}
